### PR TITLE
support unity3d work.

### PR DESCRIPTION
**Pull request by Hxms**
support unity3d work.modify some features..

### CODE REVIEW

**Comment by Hxms** [comment]
work on unity3d.ios has some bug, need fix....

**Comment by Hxms** [comment]
work on unity3d.ios has some bug, need fix....

**Comment by Hxms** [comment]
work on unity3d.ios has some bug, need fix....

**Comment by Hxms** [comment]
work on unity3d.ios has some bug, need fix....

**Comment by Hxms** [comment]
work on unity3d.ios has some bug, need fix....

**Comment by longshine** [comment]
Thanks for your contribution. I've committed some complementary changes, hoping you wouldn't  mind:

- restore use of Interlocked to avoid many changes in System namespace. Instead, I added a <code>using Interlocked = Mina.Util.InterlockedUtil;</code> on the top of those files.
- move your solution file to a separate Mina.NET20.Unity3D.sln

You're welcome to submit a pull request again whenever you fix it : )

Besides, would you like to try the Mina project for .NET40? It has better performance, but I'm not sure if it works on Unity3D.

**Comment by Hxms** [comment]
I don't Sure,i can try...
You're welcome

**Pull request merged**
